export type RuleErrorCode =
  | 'UNKNOWN_ACTION'
  | 'GAME_ALREADY_OVER'
  | 'NOT_YOUR_TURN'
  | 'WRONG_PHASE'
  | 'PENDING_INTERACTION_REQUIRED'
  | 'INVALID_TARGET'
  | 'INSUFFICIENT_RESOURCES'
  | 'INSUFFICIENT_BANK_RESOURCES'
  | 'NO_PIECES_REMAINING'
  | 'EDGE_OCCUPIED'
  | 'EDGE_NOT_CONNECTED'
  | 'VERTEX_OCCUPIED'
  | 'DISTANCE_RULE_VIOLATION'
  | 'ROAD_CONNECTION_REQUIRED'
  | 'HOUSE_REQUIRED_FOR_UPGRADE'
  | 'DICE_ALREADY_ROLLED'
  | 'DICE_ROLL_REQUIRED'
  | 'INVALID_DISCARD'
  | 'INVALID_ROBBER_DESTINATION'
  | 'INVALID_STEAL_TARGET'
  | 'INVALID_TRADE'
  | 'TRADE_ID_IN_USE'
  | 'TRADE_NOT_FOUND'
  | 'TRADE_STALE'
  | 'CARD_NOT_OWNED'
  | 'CARD_BOUGHT_THIS_TURN'
  | 'CARD_PLAY_LIMIT_REACHED'
  | 'CARD_TARGET_UNAVAILABLE'
  | 'DECK_EMPTY';

export interface RuleError {
  readonly code: RuleErrorCode;
  readonly message: string;
}
